name: Deploy develop threisd-telegram-chatbot
run-name: ${{ github.actor }} is deploying develop branch🚀
on:
  push:
    branches:
      - "main"
jobs:
  prepare-env:
    name: Prepare ENV
    runs-on: [self-hosted, runner_dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare ENV
        run: |
          echo "${{ secrets.NGROK_AUTHTOKEN }}" >> .env
          echo "${{ secrets.BOT_TOKEN }}" >> .env
          echo "${{ vars.SOCKET_ADDR }}" >> .env
          echo "${{ vars.WEBHOOK_DOMAIN }}" >> .env
  # compile:
  #   name: Compile
  #   runs-on: [self-hosted, runner_dev]
  #   needs: [lint, prepare-env]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup Rust
  #       uses: dtolnay/rust-toolchain@stable
  #     - name: Compile
  #       run: cargo build -r --verbose
  # test:
  #   name: Test
  #   runs-on: [self-hosted, runner_dev]
  #   needs: [lint, prepare-env, compile]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup Rust
  #       uses: dtolnay/rust-toolchain@stable
  #     - name: Run test
  #       run: cargo test --verbose
  # func:
  #   name: Run the work
  #   runs-on: [self-hosted, runner_dev]
  #   needs: [lint, prepare-env, compile, test]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup Rust
  #       uses: dtolnay/rust-toolchain@stable
  #     - name: Run executable
  #       run: pm2 restart pm2-job.json
